WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.client:Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 124, in on_message
    user_message_counts[user_id][pastry_modifier] += pastry_multiplier
NameError: name 'pastry_modifier' is not defined
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.client:Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 126, in on_message
    save_data(user_message_counts, "user_message_counts.json")
TypeError: save_data() takes 1 positional argument but 2 were given
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.client:Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 126, in on_message
    save_data(user_message_counts, "user_message_counts.json")
TypeError: save_data() takes 1 positional argument but 2 were given
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.client:Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 122, in on_message
    user_message_counts[user_id][pastry_modifier] += pastry_multiplier
NameError: name 'pastry_modifier' is not defined
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.client:Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 122, in on_message
    user_message_counts[user_id][pastry_modifier] += pastry_multiplier
NameError: name 'pastry_modifier' is not defined
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 86, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 86, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 86, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 86, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 86, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 86, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 86, in on_interaction
    # ~ ~ ~ M O D U L E S ~ ~ ~
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
ERROR:discord.app_commands.tree:Ignoring exception in command 'inventory'
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 862, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 264, in inventory
    await menu.start()
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\reactionmenu\decorators.py", line 40, in wrapper
    return await func(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\reactionmenu\views_menu.py", line 1397, in start
    raise NoPages
reactionmenu.errors.NoPages: You cannot start a menu when you haven't added any pages

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'inventory' raised an exception: NoPages: You cannot start a menu when you haven't added any pages
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.app_commands.tree:Ignoring exception in command 'inventory'
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 862, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 259, in inventory
    for member in set(karavan_data[role_str]['members']):
NameError: name 'role_str' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'inventory' raised an exception: NameError: name 'role_str' is not defined
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.app_commands.tree:Ignoring exception in command 'inventory'
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 862, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 259, in inventory
    for member in set(karavan_data[role_str]['members']):
NameError: name 'role_str' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'inventory' raised an exception: NameError: name 'role_str' is not defined
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.app_commands.tree:Ignoring exception in command 'inventory'
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 862, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 259, in inventory
    for member in set(karavan_data[role_str]['members']):
NameError: name 'role_str' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'inventory' raised an exception: NameError: name 'role_str' is not defined
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.app_commands.tree:Ignoring exception in command 'inventory'
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 862, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 263, in inventory
    if member.avatar:
AttributeError: 'str' object has no attribute 'avatar'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'inventory' raised an exception: AttributeError: 'str' object has no attribute 'avatar'
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
ERROR:discord.app_commands.tree:Ignoring exception in command 'inventory'
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 862, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 263, in inventory
    if member.avatar:
AttributeError: 'str' object has no attribute 'avatar'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'inventory' raised an exception: AttributeError: 'str' object has no attribute 'avatar'
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
ERROR:discord.app_commands.tree:Ignoring exception in command 'inventory'
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 862, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 263, in inventory
    if member.avatar:
AttributeError: 'str' object has no attribute 'avatar'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'inventory' raised an exception: AttributeError: 'str' object has no attribute 'avatar'
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.app_commands.tree:Ignoring exception in command 'inventory'
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 862, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 260, in inventory
    if member.avatar:
AttributeError: 'str' object has no attribute 'avatar'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'inventory' raised an exception: AttributeError: 'str' object has no attribute 'avatar'
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.app_commands.tree:Ignoring exception in command 'inventory'
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 862, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 261, in inventory
    print(member.avatar)
AttributeError: 'str' object has no attribute 'avatar'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'inventory' raised an exception: AttributeError: 'str' object has no attribute 'avatar'
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.app_commands.tree:Ignoring exception in command 'inventory'
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 862, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 261, in inventory
    print(member.avatar)
AttributeError: 'str' object has no attribute 'avatar'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'inventory' raised an exception: AttributeError: 'str' object has no attribute 'avatar'
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
ERROR:discord.app_commands.tree:Ignoring exception in command 'inventory'
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 862, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 265, in inventory
    if member.avatar:
AttributeError: 'str' object has no attribute 'avatar'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'inventory' raised an exception: AttributeError: 'str' object has no attribute 'avatar'
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.app_commands.tree:Ignoring exception in command 'inventory'
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 862, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 266, in inventory
    if member.avatar:
AttributeError: 'str' object has no attribute 'avatar'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'inventory' raised an exception: AttributeError: 'str' object has no attribute 'avatar'
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
ERROR:discord.app_commands.tree:Ignoring exception in command 'join'
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 862, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 143, in join
    member = interaction.guild.members[user]
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\utils.py", line 240, in __getitem__
    return self.__copied[idx]
TypeError: list indices must be integers or slices, not Member

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'join' raised an exception: TypeError: list indices must be integers or slices, not Member
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
ERROR:discord.app_commands.tree:Ignoring exception in command 'join'
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 862, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 148, in join
    print(member)
UnboundLocalError: local variable 'member' referenced before assignment

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 887, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\app_commands\commands.py", line 880, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'join' raised an exception: UnboundLocalError: local variable 'member' referenced before assignment
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
ERROR:discord.client:Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\oakne\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\oakne\Desktop\DiscordBots\KittyKaravans\Kitties&Karavans.py", line 84, in on_interaction
    await bot.tree.dispatch_interaction(interaction)
AttributeError: 'CommandTree' object has no attribute 'dispatch_interaction'
